version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '08:00'
      timezone: UTC
    versioning-strategy: increase
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
    groups:
      clack:
        applies-to: version-updates
        patterns:
          - '@clack/core'
          - '@clack/prompts'
      bun-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch

      typescript-toolchain:
        applies-to: version-updates
        patterns:
          - typescript
          - '@types/node'
          - tsx
        update-types:
          - minor
          - patch

      linting-formatting:
        applies-to: version-updates
        patterns:
          - eslint
          - 'eslint-config-*'
          - prettier
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '10:00'
      timezone: UTC
    target-branch: main
    assignees:
      - cicdbot
      - sergeyklay
      - serghei-dev
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
